id = "applescript"
name = "AppleScript"
version = "1.0.0"
schema_version = 1
authors = ["Helge Sverre <helge.sverre@gmail.com>"]
description = "AppleScript language support for Zed"
repository = "https://github.com/HelgeSverre/zed-applescript"

[grammars.applescript]
repository = "https://github.com/HelgeSverre/zed-applescript"
path = "grammars/applescript"
commit = "0c62c2d6ba25c77ba5da8ccb1cb0bde7000881b9"
